### ISSUE TITLE
Translating to german language

### ISSUE THREAD

**Issue by ondics** [ckan/ckanext-showcase#115]
Currently we are translating the extension to german language.

There are several strings to be tranlated which are already translated in the CKAN core. The extension translations replace the CKAN core translations.

Example: 

    #: ckanext/showcase/templates/header.html:9
    msgid "About"
    msgstr "Über ..."

A bad way is to translate differently than the translation in the CKAN core.

What is the best stragegy here: Not translating the string at all (commenting out in po file) **OR** Copying the translation from ckan core?

**Comment by bellisk** [comment]
Hi @ondics, sorry for the late reply to this issue. IMO, the better strategy is to comment out the strings in the po files and not translate them in our extension.

**Comment by bellisk** [comment]
Ah, I see we just merged your German translation, so this is probably not a helpful response! :) Thank you for the PR.
