### ISSUE TITLE
Pull requests being merged anymore?

### ISSUE THREAD

**Issue by ondics** [ckan/ckanext-showcase#117]
Currently there are 9 open pull requests. Can we wait for the merge to deploy the original repo in our ckan sites or shall we work with our fork?

Will the open pull requests be merged anymore? Is this repo still actively maintained?

**Comment by stefina** [comment]
Looks deserted here :( @brew @amercader @wardi You are probably working on something else, but do you need help maintaining this repo?

**Comment by amercader** [comment]
@stefina we would love some help maintaining this repo. Do you want to help reviewing and merging PRs? If so I can definitely add you to the maintainers of this repo

**Comment by stefina** [comment]
@amercader yes, I will help happily. Let's see how much availability, but the more the merrier 😅  Do you mind adding me and my team member @bellisk as well, as they are also quite deep into the topic?

**Comment by amercader** [comment]
@stefina turns out you already a maintainer for this repo 🙂

@bellisk you should have an invite to get write access too.

Thanks a lot to both of you! Feel free to review and merge any outstanding PRs, triage issues etc

**Comment by bellisk** [comment]
Thanks, @amercader!
