### ISSUE TITLE
Outdated version on Pypi

### ISSUE THREAD

**Issue by bellisk** [ckan/ckanext-showcase#132]
The version on https://pypi.org/project/ckanext-showcase/ is v1.0.3, which is quite outdated. I can't update it because I'm not a maintainer. @amercader or @brew, could you please add my user, https://pypi.org/user/bellisk/ there please? (Or update the package, either works. :slightly_smiling_face:) Thank you!

**Comment by amercader** [comment]
@bellisk you are now a maintainer for that PyPI package, thanks!

**Comment by bellisk** [comment]
Thanks, @amercader! I've uploaded v1.4.6. :D
