### ISSUE TITLE
AttributeError: `add_ckan_admin_tab` not found in plugins toolkit

### ISSUE THREAD

**Issue by tremblaysimon** [ckan/ckanext-showcase#20]
I think showcase plugin doesn't support ckan 2.3 as it says in README.rst since add_ckan_admin_tab seems to be added since 2.4: http://docs.ckan.org/en/ckan-2.4.1/extensions/plugins-toolkit.html#ckan.plugins.toolkit.add_ckan_admin_tab

**Comment by brew** [comment]
This _should_ still work for 2.3, as Showcase performs a version check before using the `add_ckan_admin_tab` toolkit method.

What exact version of CKAN are you using? You can use http://yourckandomain.com/api/action/status_show to find the CKAN version.

**Comment by tremblaysimon** [comment]
ckan 2.3.2

Maybe it's because the version check max is 2.3 that doesn't work as expected?

**Comment by brew** [comment]
Yes, that looks likely - thanks for the report. If you're able to submit a PR that would be great, otherwise, I'll try to get to this sometime soonish.

**Comment by brew** [comment]
Fixed in #21.
