### ISSUE TITLE
Word-wrapping issue in "Datasets in Showcase"

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-showcase#5]
![manhattan_payphone_linknyc_explorer_-_showcases_-_betanyc_s_community_data_portal](https://cloud.githubusercontent.com/assets/1980690/7019850/1a69c4da-dce2-11e4-852a-4bb99dd18232.jpg)

Perhaps, do a **word-wrap: break-word**?

**Comment by brew** [comment]
Thanks!
