### ISSUE TITLE
Update on CKAN 2.9 support?

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-showcase#91]
ckanext-pages is listed as one of the most used extensions in https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions

I see there is an open PR for Python 3 support (#75).

Now that 2.9 is released, wondering what's the status.

**Comment by amercader** [comment]
Tag `v1.4.0` supports CKAN 2.9 / Python 3. Thanks @smotornyuk and @pdelboca for work on this
